#!/bin/bash

choose () {
    local PS3="Choose a file to edit: "
    select opt in $(find . -name *$1*) quit
    do
        if [[ $opt = "quit" ]]
        then
            break
        fi
        ${EDITOR:-vim} "$opt"
    done
}

choose $1
