#!/bin/bash

if [ "$1" = "" ]
then
ssh 192.168.0.27 -l sunly
elif [ "$1" != "" -a "$2" != "" -a "$3" == "" ]
then
ssh $1 -l $2
else
echo "*******************************************************"
echo "Usage:"
echo -e " 1.Ssh_popule\t\t--> ssh 192.168.0.27 -l sunly"
echo -e " 2.Ssh_popule \$1 \$2\t--> ssh \$1 -l \$2"
echo "*******************************************************"
fi
